import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
  return(
    <header className="bg-orange-700 py-4">
      <div className="container mx-auto px-10 text-white font-bold">
        <nav className="flex items-center justify-between">
          <div className="flex items-center">
            <Link href="/">Student Leader (SL) Yusrat Miah Homepage</Link>
          </div>
          <div>
            <Link href="/cid-info">What is CID?</Link>
          </div>
          <div>
            <Link href="/about-me">About Me</Link>
          </div>
          <div>
            <Link href="/contact-me">Contact Me</Link>
          </div>
        </nav>
      </div>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
